---
abstract: 'an example developer release'
author:
  - 'Neil Bowers <neil@bowers.com>'
build_requires:
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.013, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-TestDist-Developer
requires:
  perl: 5.006
  strict: 0
  warnings: 0
resources:
  homepage: https://github.com/neilbowers/Acme-TestDist-Developer
  repository: https://github.com/neilbowers/Acme-TestDist-Developer.git
version: 0.01_01
